const test=require('node:test');
const assert=require('node:assert/strict');
const {start,synthetic}=require('./helpers');
test('single workbook imports both kinds; target/date/page and cleanup stay consistent', {timeout:120000}, async t=>{
  const {page,errors}=await start(t);
  await page.locator('#fileInput').setInputFiles(synthetic());
  await page.locator('#datasetTarget').waitFor({state:'visible',timeout:5000});
  await page.waitForFunction(()=>document.querySelector('#datasetTarget')?.options.length>=2);
  assert.match(await page.locator('#datasetTarget').innerText(),/合成人物甲/);
  await page.waitForFunction(()=>document.querySelector('#callPageSummary')?.textContent.includes('1,101'));
  assert.equal(await page.locator('#callRows tr').count(),500);
  await page.locator('#callNextPage').click();
  await page.waitForFunction(()=>document.querySelector('#callPageSummary')?.textContent.includes('第 2'));
  await page.locator('button[data-view="network"]').click();
  await page.waitForFunction(()=>document.querySelector('#datasetRows')?.textContent.includes('192.0.2.1'));
  await page.locator('#datasetTarget').selectOption('0900000002');
  await page.waitForFunction(()=>document.querySelector('#datasetPageInfo')?.textContent.includes('共 0'));
  await page.locator('button[data-view="profile"]').click();
  await page.waitForFunction(()=>document.querySelector('#profileContent')?.textContent.includes('合成人物乙'));
  assert.doesNotMatch(await page.locator('#profileContent').innerText(),/合成人物甲/);
  await page.locator('#datasetTarget').selectOption('0900000001');
  await page.locator('button[data-view="calls"]').click();
  await page.locator('#datasetStart').fill('2026-01-02');await page.locator('#datasetEnd').fill('2026-01-02');
  await page.locator('#datasetDateApply').click();
  await page.waitForFunction(()=>document.querySelector('#callPageSummary')?.textContent.includes('共 501'));
  await page.locator('#datasetClear').click();
  await page.waitForFunction(()=>document.querySelector('#datasetStatus')?.textContent.includes('已清除'));
  assert.equal(await page.locator('#datasetRows tr').count(),0);
  assert.deepEqual(errors,[]);
});

test('exports scoped XLSX/network PDF, cancels import, and clears orphan sessions on reload', {timeout:120000}, async t=>{
  const {page,context,errors}=await start(t);
  await page.locator('#fileInput').setInputFiles(synthetic(5));
  await page.waitForFunction(()=>document.querySelector('#datasetTarget')?.options.length===2);
  await page.locator('#attachmentExportButton').click();
  const downloadPromise=page.waitForEvent('download');await page.locator('#attachmentXlsxButton').click();
  const file=await downloadPromise;
  const fs=require('node:fs'),ExcelJS=require('../../vendor/exceljs.min');
  const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(fs.readFileSync(await file.path()));
  assert.ok(workbook.getWorksheet('網路歷程'));
  assert.match(JSON.stringify(workbook.getWorksheet('網路歷程').getSheetValues()),/192.0.2.1/);
  assert.doesNotMatch(JSON.stringify(workbook.getWorksheet('用戶資料').getSheetValues()),/合成人物乙/);
  await page.waitForFunction(()=>!document.querySelector('#attachmentXlsxButton').disabled);
  const pdfPromise=page.waitForEvent('download');await page.locator('[data-attachment-pdf="network"]').click();
  const pdf=await pdfPromise;assert.equal(fs.readFileSync(await pdf.path()).subarray(0,4).toString(),'%PDF');
  await page.waitForFunction(()=>!document.querySelector('#attachmentXlsxButton').disabled);
  await page.locator('#attachmentExportCloseButton').click();
  const peer=await context.newPage();await peer.goto(page.url());await peer.locator('#noticeDismissButton').click();
  await peer.locator('#fileInput').setInputFiles(synthetic(3));await peer.waitForFunction(()=>document.querySelector('#datasetTarget')?.options.length===2);
  assert.equal((await page.evaluate(()=>indexedDB.databases())).filter(d=>d.name.startsWith('phone-workbench-session-')).length,2);
  await peer.close();await page.reload();await page.locator('#noticeDismissButton').click();
  await page.locator('#fileInput').setInputFiles(synthetic(2));await page.waitForFunction(()=>document.querySelector('#datasetTarget')?.options.length===2);
  assert.equal((await page.evaluate(()=>indexedDB.databases())).filter(d=>d.name.startsWith('phone-workbench-session-')).length,1);
  await page.locator('#fileInput').setInputFiles(synthetic(50000));
  await page.locator('#datasetImportCancel').click();
  await page.locator('#importProgressModal').waitFor({state:'hidden'});
  await page.locator('button[data-view="network"]').click();
  await page.waitForFunction(()=>document.querySelector('#datasetRows')?.textContent.includes('192.0.2.1'));
  assert.deepEqual(errors,[]);
});
test('legacy overlap, JSON subject volumes, quota failure and rapid target changes preserve data', {timeout:120000}, async t=>{
  const {page,errors}=await start(t);
  const requests=[]; page.on('request',r=>requests.push(r));
  const wb=require('../../vendor/xlsx.full.min');
  const old=wb.utils.book_new();wb.utils.book_append_sheet(old,wb.utils.aoa_to_sheet([
    ['電話號碼：0900000001'],
    ['始話時間','通話秒數','調閱號碼','IMEI','通話類別','通話對象','轉接電話','基地台/交換機','備註'],
    ['2026-01-01T01:00:00',30,'0900000001','','發話','0900000002','0900000009','SYNTH-1',''],
    ['','','','','','','','SYNTH-2','']
  ]),'通聯紀錄');
  await page.locator('#fileInput').setInputFiles({name:'synthetic-legacy.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(wb.write(old,{type:'buffer',bookType:'xlsx'}))});
  await page.waitForFunction(()=>document.querySelector('#callPageSummary')?.textContent.includes('共 1'));
  assert.match(await page.locator('#callRows').innerText(),/0900000009/);
  const subjects=Array.from({length:501},(_,i)=>({phone:'0900000001',subject:{'用戶名稱':`合成用戶 ${i}`},source_sheet:'使用者資料',row_number:i+2}));
  const input={case:{source_file:'synthetic.json'},records:[{target_phone:'0900000001',occurred_at:'2026-01-01T01:00:00',call_type:'發話',counterparty_phone:'0900000002'}],base_stations:[],subjects};
  await page.locator('#fileInput').setInputFiles({name:'synthetic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(input))});
  await page.waitForFunction(()=>document.querySelector('#importProgressModal')?.hidden && document.querySelector('#callPageSummary')?.textContent.includes('共 1'));
  await page.locator('#dataExportViewButton').click();
  const downloaded=[];page.on('download',d=>downloaded.push(d));
  await page.locator('#exportWorkspaceButton').click();
  await page.waitForFunction(()=>document.querySelector('#datasetJsonCancel')?.hidden);
  assert.equal(downloaded.length,2);
  const fs=require('node:fs');const exports=await Promise.all(downloaded.map(async d=>({name:d.suggestedFilename(),mimeType:'application/json',buffer:fs.readFileSync(await d.path())})));
  assert.equal(exports.map(f=>JSON.parse(f.buffer).subjects.length).reduce((a,b)=>a+b,0),501);
  await page.locator('#fileInput').setInputFiles(exports);
  await page.waitForFunction(()=>document.querySelector('#importProgressModal')?.hidden && document.querySelector('#callPageSummary')?.textContent.includes('共 1'));
  await page.locator('button[data-view="profile"]').click();
  await page.locator('[data-dataset-page="next"]').click();
  await page.waitForFunction(()=>document.querySelector('#profileContent')?.textContent.includes('合成用戶 500'));
  const worker=page.workers().find(w=>w.url().includes('dataset-worker'));
  await worker.evaluate(()=>{navigator.storage.estimate=async()=>({quota:1,usage:1});});
  await page.locator('#fileInput').setInputFiles(synthetic(3));
  await page.waitForFunction(()=>document.querySelector('#importStatus')?.textContent.includes('空間不足'));
  assert.match(await page.locator('#profileContent').innerText(),/合成用戶 500/);
  await worker.evaluate(()=>{delete navigator.storage.estimate;});
  await page.locator('#fileInput').setInputFiles(synthetic(3));
  await page.waitForFunction(()=>document.querySelector('#datasetTarget')?.options.length===2);
  for(const target of ['0900000002','0900000001','0900000002']) await page.locator('#datasetTarget').selectOption(target);
  await page.waitForFunction(()=>document.querySelector('#callsView')?.getAttribute('aria-busy')==='false' && document.querySelector('#callRows tr td:nth-child(4)')?.textContent==='0900000002');
  assert.doesNotMatch(await page.locator('#callRows').innerText(),/0900000001/);
  assert.ok(requests.every(r=>r.method()==='GET' && new URL(r.url()).origin===new URL(page.url()).origin));
  assert.deepEqual(errors,[]);
});
test('legacy explicit subject phone stays associated when records contain multiple targets', {timeout:60000}, async t=>{
  const {page}=await start(t);
  const input={case:{source_file:'synthetic.json',source_formats:['multi_phone_streaming_xlsx'],subject:{'電話號碼':'0900000001','用戶名稱':'合成舊版案主'}},records:['0900000001','0900000002'].map(target_phone=>({target_phone,occurred_at:'2026-01-01T01:00:00',call_type:'發話'})),base_stations:[]};
  await page.locator('#fileInput').setInputFiles({name:'synthetic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(input))});
  await page.waitForFunction(()=>document.querySelector('#datasetTarget')?.options.length===2);
  await page.locator('button[data-view="profile"]').click();
  await page.waitForFunction(()=>document.querySelector('#profileContent')?.textContent.includes('合成舊版案主'));
  await page.locator('#datasetTarget').selectOption('0900000002');
  await page.waitForFunction(()=>document.querySelector('#profileView')?.getAttribute('aria-busy')==='false');
  assert.doesNotMatch(await page.locator('#profileContent').innerText(),/合成舊版案主/);
});
